autoInstallPeers: false
catalog:
  "@types/node": ^26.0.0
  "typescript": ^6.0.2
  "vite": ^8.3.1
  "vitest": ^4.1.2
  "@vitest/coverage-v8": ^4.1.2
  "zod": ^4.6.5

engineStrict: true
injectWorkspacePackages: true
minimumReleaseAge: 1440
packages:
  - 'apps/*'
  - 'packages/*'
