name: renovate

on:
  schedule:
    - cron: "17 */4 * * *"
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Renovate log level'
        type: choice
        options:
          - debug
          - info
        default: info

concurrency:
  group: renovate
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.RENOVATE_APP_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
        id: renovate-app-token
      - uses: renovatebot/github-action@1cd96b855fee0da6f230617e89dbff0e06ea393a # v46.3.5
        env:
          LOG_LEVEL: ${{ inputs.log_level || 'info' }}
          RENOVATE_DOCKER_MAX_PAGES: 10
          RENOVATE_PLATFORM_COMMIT: enabled
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          renovate-image: "docker.io/renovate/renovate:44.117.2@sha256:5e9ea3e65b3e8e7c0caf813214ed0705827433b7ea19e65f697083cca3a9c0e7"
          token: ${{ steps.renovate-app-token.outputs.token }}
