name: renovate

on:
  schedule:
    - cron: "17 */4 * * *"
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Renovate log level'
        type: choice
        options:
          - debug
          - info
        default: info

concurrency:
  group: renovate
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.RENOVATE_APP_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
        id: renovate-app-token
      - uses: renovatebot/github-action@6d26fcf0275dc65624cbc3d51fe78bc773f98321 # v46.3.6
        env:
          LOG_LEVEL: ${{ inputs.log_level || 'info' }}
          RENOVATE_DOCKER_MAX_PAGES: 10
          RENOVATE_PLATFORM_COMMIT: enabled
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          renovate-image: "docker.io/renovate/renovate:44.126.1@sha256:a49e9555e14cf51018cc819a45e15022b9151c601eb44141a18be5080701c352"
          token: ${{ steps.renovate-app-token.outputs.token }}
